# Generated by Django 5.2.15 on 2026-06-23 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
