# Generated by Django 5.2.15 on 2026-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='offers_personal_training',
            field=models.BooleanField(default=False),
        ),
    ]
