# Generated by Django 5.2.15 on 2026-06-23 10:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_program_programpackage'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='program_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='activities.programpackage'),
        ),
        migrations.AlterField(
            model_name='client',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='client',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
