# Generated by Django 5.2.15 on 2026-06-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_program_package_alter_client_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
    ]
