# Generated by Django 5.2.15 on 2026-06-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0004_alter_program_program_type'),
        ('clients', '0004_client_payment_method_alter_payment_method'),
        ('trainers', '0004_trainer_offers_personal_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_training', models.BooleanField(default=False)),
                ('join_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=10)),
                ('action', models.CharField(choices=[('new', 'New Enrollment'), ('renewal', 'Renewal'), ('upgrade', 'Package Upgrade')], default='new', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='accounts.gym')),
                ('program_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.programpackage')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer')),
            ],
            options={
                'db_table': 'membership_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
