# Generated by Django 5.2.15 on 2026-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_membershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='recognized_month',
            field=models.DateField(blank=True, help_text='Month this payment is attributed to in revenue reports. Defaults to expiry_date for base packages, today for add-ons.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recognized_month',
            field=models.DateField(blank=True, help_text='Month this payment is attributed to in revenue reports.', null=True),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='action',
            field=models.CharField(choices=[('new', 'New Enrollment'), ('renewal', 'Renewal'), ('upgrade', 'Package Upgrade'), ('addon', 'Add-on')], default='new', max_length=20),
        ),
    ]
