# Generated by Django 5.2.15 on 2026-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_membershiphistory_recognized_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
