# Generated by Django 5.2.15 on 2026-06-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_program_programpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('regular_membership', 'Regular Membership'), ('offer', 'Offer'), ('other', 'Other')], default='regular_membership', max_length=30),
        ),
    ]
