# Generated by Django 5.2.15 on 2026-06-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_program_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('general', 'General'), ('personal_training', 'Personal Training')], default='general', max_length=30),
        ),
    ]
