# Generated by Django 5.2.15 on 2026-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_program_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('general', 'General'), ('personal_training', 'Personal Training'), ('regular_membership', 'Regular Membership'), ('offer', 'Offer / Special'), ('other', 'Other Activity')], default='regular_membership', max_length=30),
        ),
    ]
